baseURL = "http://www.falseneutral.net/"
languageCode = "en-us"
title = "Technical Things"
theme = "coder"

[params]
author = "Luigi Coccia"
info = "Computers and the bits between them"
description = "Luigi Coccia's personal website"
keywords = "blog,developer,architect,personal,code,computers,networks,security"

[[params.social]]
name = "Github"
weight = 1
url = "https://github.com/falseneutral/"

[[params.social]]
name = "Twitter"
weight = 2
url = "https://twitter.com/falseneutral/"

[[params.social]]
name = "LinkedIn"
weight = 3
url = "https://www.linkedin.com/in/ginococcia/"

[[menu.main]]
name = "Blog"
weight = 1
url = "/posts/"

[[menu.main]]
name = "About"
weight = 2
url = "/about/"
